package com.gualoto.pfinaldm.ui.core


import com.gualoto.pfinaldm.data.network.entities.news.Data

fun Data.toNewsUI() = NewsUI(
        id =this.mal_id,
        title = this.title,
        date = this.date,
        excerpt = this.excerpt,
        imageUrl = this.images.jpg.image_url,
        url = this.url,
        author_username = this.author_username,
        comments= this.comments
)

data class NewsUI(
        val id: Int,
        val title: String,
        val date: String,
        val excerpt: String,
        val imageUrl: String,
        val url: String,
        val comments: Int, // Asegúrate de tener esta propiedad si es necesario
        val author_username: String,
)

fun com.gualoto.pfinaldm.data.network.entities.anime.topAnime.Data.toTopAnimeUI() = TopAnimeUI(
    aired = this.aired,
    airing =  this.airing,
    approved =  this.approved,
    background =  this.background,
    broadcast =  this.broadcast,
    demographics =  this.demographics,
    duration = this.duration,
    episodes =  this.episodes,
    explicit_genres =  this.explicit_genres,
    favorites =  this.favorites,
    genres =  this.genres,
    imageUrl =  this.images.jpg.image_url,
    licensors = this.licensors,
    id =  this.mal_id,
    members =  this.members,
    popularity =  this.popularity,
    producers =  this.producers,
    rank =  this.rank,
    rating = this.rating,
    score =  this.score,
    scored_by =  this.scored_by,
    season =  this.season,
    source =  this.source,
    status =  this.status,
    studios =  this.studios,
    synopsis =  this.synopsis,
    themes =  this.themes,
    title =  this.title,
    title_english =  this.title_english,
    title_japanese =  this.title_japanese,
    title_synonyms =  this.title_synonyms,
    titles =  this.titles,
    trailer =  this.trailer,
    type =  this.type,
    url =  this.url,
    year = this.year
)

fun com.gualoto.pfinaldm.data.network.entities.anime.season.now.Data.toSeasonAnimeUI() = SeasonAnimeUI(
     aired =this.aired,
     airing = this.airing,
     approved =  this.approved,
     background = this.background,
     broadcast =  this.broadcast,
     demographics =  this.demographics,
     duration =  this.duration,
     episodes =  this.episodes,
     explicit_genres =  this.explicit_genres,
     favorites =  this.favorites,
     genres = this.genres,
     imageUrl =  this.images.jpg.image_url,
     licensors =  this.licensors,
     id =  this.mal_id,
     members =  this.members,
     popularity =  this.popularity,
     producers =  this.producers,
     rank =  this.rank,
     rating =  this.rating,
     score =  this.score,
     scored_by =  this.scored_by,
     season =  this.season,
     source =  this.source,
     status =  this.status,
     studios =  this.studios,
     synopsis =  this.synopsis,
     themes =  this.themes,
     title =  this.title,
     title_english = this.title_english,
     title_japanese = this.title_japanese,
     title_synonyms =  this.title_synonyms,
     titles =  this.titles,
     trailer =  this.trailer,
     type =  this.type,
     url =  this.url,
     year =  this.year
)


fun com.gualoto.pfinaldm.data.network.entities.anime.season.upcoming.Data.toSeasonUAnimeUI() = SeasonUAnimeUI(
    aired = this.aired,
    airing =  this.airing,
    approved =  this.approved,
    background =  this.background,
    broadcast =  this.broadcast,
    demographics =  this.demographics,
    duration = this.duration,
    episodes =  this.episodes,
    explicit_genres =  this.explicit_genres,
    favorites =  this.favorites,
    genres =  this.genres,
    imageUrl =  this.images.jpg.image_url,
    licensors = this.licensors,
    id =  this.mal_id,
    members =  this.members,
    popularity =  this.popularity,
    producers =  this.producers,
    rank =  this.rank,
    rating = this.rating,
    score =  this.score,
    scored_by =  this.scored_by,
    season =  this.season,
    source =  this.source,
    status =  this.status,
    studios =  this.studios,
    synopsis =  this.synopsis,
    themes =  this.themes,
    title =  this.title,
    title_english =  this.title_english,
    title_japanese =  this.title_japanese,
    title_synonyms =  this.title_synonyms,
    titles =  this.titles,
    trailer =  this.trailer,
    type =  this.type,
    url =  this.url,
    year = this.year
)
